name: computorbuild
channels:
  - conda-forge
dependencies:
  - r-base=4.1.2
  - r-raster
  - r-codetools
  - r-remotes
  - r-reticulate
  - r-rmarkdown
  - r-tidyverse
  - r-plotly
  # - r-devtools
  - r-lubridate
  - r-cowplot
  - r-sf
  - r-stringi
  - r-kableextra
  - r-ggtext
  - r-wesanderson
  - r-highcharter
  - r-janitor

  
  
  
